### ISSUE TITLE
Register web data connector asynchronously?

### ISSUE THREAD

**Issue by tehandyb** [tableau/webdataconnector#141]
Is there a way to register my connector later on after the user has done some action on the page?

My problem is that I have some user interaction that will generate the request URL that will be requested in the .getData function. But, if I register with the getData function, I can't re-set the getData function later on. And it looks like all the values in the getData function somehow become immutable when I register the connector even if the values are coming from outside the scope of that function.

**Comment by lbrendanl** [comment]
What do you mean by 'register with the getData function'?  

For the general pattern of the user specifying some parameter through the UI of the WDC, we suggest using the tableau.connectionData property.  Because of the two phase model of WDC (interactive and gather data), tableau.connectionData is the only way to send state between the two phases.

So what you can do is gather the request URL from the user in the interactive phase, store that URL in the tableau.connectionData property, and then read that property during the gather data phase (in the getData method).

**Comment by joelperry93** [comment]
I have a very similar issue. It seems to want me to define the getData and getSchema methods straight away in the interactive phase (otherwise it complains that I haven't registered my connector), but I require some interactivity from the user before I decide on the schema or retrieve the data that I want to post through. I have spent a very long time trying to figure out how to get this to work but there doesn't seem to be anyway I can define getData at the beginning, before I get the data I want, and have it come through at the end. Would *very* much appreciate any help.

**Comment by lbrendanl** [comment]
So I think there's just a slight misunderstanding of how the phases work.  You implement the entire interface of the connector up front - for simplicity sake let's assume it's in a single JavaScript file.  In that file, you'll define the getSchema method and getData method, in addition to some other important stuff like registerConnector.

When your connector is loaded, it will be running in one of the two phases, but it's the same code that is loaded and executed.  

The scenario of gathering data from the user and using that data in the getSchema or getData is definitely possible (and one of the primary use cases of WDC).  The flow goes like this:

- My connector is loaded in the interactive phase.
- The user inputs some parameter.
- The connector grabs the parameter via JavaScript (i.e. you could read a value from a dropdown via JavaScript when a "Submit" is clicked. (before tableau.submitI() ) is executed.   
- Store the parameter in the tableau.connectionData property. 
- Now the interactive phase ends when tableau.submit is called.  
- The data gathering phase will then begin.
- getSchema() wiill be called first, followed by getData().  In both those functions you can access the parameter by reading from the tableau.connectionData property.


A working example of this can be found in one of our tutorials: [http://tableau.github.io/webdataconnector/docs/wdc_multi_table_tutorial](http://tableau.github.io/webdataconnector/docs/wdc_multi_table_tutorial
) 

Does that help? Or am I misunderstanding your use case?

**Comment by tehandyb** [comment]
Thank you! That fixed my problem. I think this connectionData property should be highlighted more in the tutorial because I probably would've never found it if you hadn't shown it, just a friendly suggestion :)

Also one thing I noticed was that the tableau.connectionData was an empty string by default, so I had to change it to an object if I wanted to add more data to it(for example I also wanted the user to be able to specify their own table name alias). 
Maybe its prop type should be object instead of a string? I noticed because of the React proptype warning in the console. Thanks!

**Comment by joelperry93** [comment]
Thank you as well! I have managed to get something working now. If I understand correctly, you do need to have getData and getSchema defined initially during each phase, but because you can access tableau.connectionData, you can still dynamically build the schema etc that you want based off user data. Thanks again!

**Comment by lbrendanl** [comment]
Thanks for the feeback @tehandyb, you are totally right on there, we should highlight that more.  I'd need to dig into the prop type issue a bit, thanks for bringing it up. 

Glad to hear both of you are unblocked!  Am going to close the issue now.
