### ISSUE TITLE
Column alias disappears after data loaded

### ISSUE THREAD

**Issue by ataft** [tableau/webdataconnector#200]
The following screenshots show what happens (highlighted in yellow) when using the "Earthquake USGS" Web Data Connector example from the Simulator v2.1.0 in Tableau Public 10.3.2:

As you can see in the code, the alias for the magnitude column is "magnitude":
![image](https://user-images.githubusercontent.com/11670864/29689988-fd6c25a2-88d9-11e7-9955-4076b4922c39.png)

When the data is initially loaded, the alias appears OK:
![image](https://user-images.githubusercontent.com/11670864/29689834-7a4d3b98-88d9-11e7-85b1-53c3b301f7e5.png)

However, when you go to the worksheet, the alias is gone and the id appears:
![image](https://user-images.githubusercontent.com/11670864/29689857-9071713c-88d9-11e7-938d-975ff1d0cb3c.png)

If you go back to the Data Source, then the alias is completely gone:
![image](https://user-images.githubusercontent.com/11670864/29690077-5abb2a00-88da-11e7-8e2d-1a14aee3c437.png)

**Comment by lbrendanl** [comment]
Thank for reporting this!  This looks to be clearly a bug in our Desktop product.  I have opened a bug internally to track this, and we will get this fixed in an upcoming release.  

I'll be closing this GitHub issue since this mainly tracks the Simulator project and the code fix will happen in our Desktop product.  

Thanks again.

**Comment by ataft** [comment]
I thought it was a bug in the Desktop product too, but I just tried Tableau 10.3.2 connected to a SQL Server Database, and the "id" and "alias" fields appear to work just fine, as shown here:
![image](https://user-images.githubusercontent.com/11670864/29692261-ece407ae-88e3-11e7-8d89-7d77f30e8ea7.png)

Both the Web Data Connector and SQL Server appear to work fine at the beginning, in that what the Web Connector calls "id" is being set to "Remote Field Name" in the Desktop and "alias" is being set to "Field Name". Going to the worksheet breaks the web connector (as you've seen), but not the database connector.

Is it possible that there's another attribute other than "id" and "alias" that needs to be set, something like "remote"?

Perhaps the Web Data Connector documentation should let people know that the "alias" attribute currently has a bug and shouldn't be used...

**Comment by xpujol-userzoom** [comment]
I'm currently experiencing this same bug in a Web Data Connector I'm building.

@ataft I think we are indeed using the correct attributes. As far as I can see there are no other relevant attributes to be set, according to the [API ref](https://tableau.github.io/webdataconnector/docs/api_ref.html#webdataconnectorapi.columninfo). It looks like there is a mapping between "id"->"Remote Field Name" and "alias"->"Field name", which breaks as soon as the user switches to the Sheet tab due to a bug.

@lbrendanl is there a Tableau Desktop bug tracker in which I can follow up on this issue? Or a way to be notified when this bug fix is released? Thanks.
