### ISSUE TITLE
Defining columns property in tableSchema from API JSON response

### ISSUE THREAD

**Issue by AChPe** [tableau/webdataconnector#241]
Hi!

We are trying to modify the getSchema function in the WDC to include a $.getJSON call to our API so that we can use the API response to generate the cols array in the columns property of the tableSchema object, which is then put into the schemaCallback to define our table. To give some background, our response is an Array of Objects with multiple properties 
(e.g. [ { prop1: , prop2: , ...}, { prop1: , prop2: , ...}, ...]

So, in short, what we try to achieve is to automatically generate the cols array from our API response.

 We are trying to do this with the following script:

$.getJSON(apiCall, function (resp) {
    var cols2 = Object.keys(resp[0])
    .map(function (obj) {
        var dataValue = (typeof (resp[0][obj])) == 'number' ? 'tableau.dataTypeEnum.float' : 
                                   'tableau.dataTypeEnum.dateTime';
        var column = { id: obj, alias: obj, dataType: dataValue };
        return column
    });
});

var tableSchema = {
    id: "Model",
    alias: "Model Trial",
    columns: cols2
};

When we run this script locally on our API response it correctly returns the desired cols2 array which we can input to the columns property of the tableSchema object. However, when we try to run it in the WDC it is always crashing Tableau.

Any idea of what could be the problem, or how we could solve this issue?

Thanks in advance!

**Comment by benlower** [comment]
@AChPe sorry about this! we think it is due to the fact that we are currently using an old, webkit-based browser in Tableau Desktop. we are going to address this later this year by upgrading to a current, webengine-based browser. in the meantime you could try to install the Qt 5.4 SDK and use the sample browser app to see if you can repro and debug the issue. alternatively, an older version of the Otter Browser (https://github.com/OtterBrowser/otter-browser/releases/tag/v0.9.12) might work for this too. i suspect you are using something in your JS that is not supported in webkit.
