### ISSUE TITLE
tableauwdc-1.1.0.js in master is different from the version used in the simulator

### ISSUE THREAD

**Issue by wcandillon** [tableau/webdataconnector#27]
There seems to be major differences between tableauwdc-1.1.0.js in master and the version used in the examples. What is the root cause of these differences?

**Comment by lbrendanl** [comment]
The only difference is that 1.1.1 added a very small messaging change to support the new simulator.  Functionally, and within Tableau Desktop, they are identical.

Moving forward we won't be keeping versions of the js file in GitHub (because it's the portion of the SDK that we can't accept pull requests on due to it's dependency on our native platform code).  

Instead, we will host all versions of this file here:
https://connectors.tableau.com/libs/

All samples in master use https://connectors.tableau.com/libs/tableauwdc-1.1.0.js.  All samples in the hosted simulator also use this file (with the exception of the Google Sheets Connector).  See the "On WDC Versioning" section of the README for details on this.
