### ISSUE TITLE
flex CSS property is not supported in browser

### ISSUE THREAD

**Issue by AndreyWrike** [tableau/webdataconnector#281]
It looks like native WDC browser does not support "flex" CSS property
https://developer.mozilla.org/en-US/docs/Web/CSS/flex

which makes our product's login page render badly
is there a way to workaround this or open in another browser?

**Comment by KeshiaRose** [comment]
Hi Andrey,

Improving the browser for WDCs is one of our top priorities right now and we are currently working on upgrades to include more modern browser capabilities. Unfortunately, this work will not be released for quite a while and until then flex styling will not work. Since there is no way for your WDC to be opened in another browser you will have to style your login page to be backwards compatible: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Backwards_Compatibility_of_Flexbox

Take care,
Keshia

**Comment by contra** [comment]
@KeshiaRose Any progress on this?
