### ISSUE TITLE
Tableau log not displayed

### ISSUE THREAD

**Issue by mradamlacey** [tableau/webdataconnector#33]
The 1.1.0 version of the WDC simluator displays messages written with `tableau.log` in the bottom area of the Simulator UI.

I see that `tableau.log` is still part of the WDC 1.1.1 API, but none of the message being written are displayed anywhere.  Is there something I need to do to display the tableau log?

**Comment by lbrendanl** [comment]
Oops that's a bug.  We removed the duplicate log entries at the bottom of the simulator because we felt it was overkill to have the logs spit out there and also as expected in the console window.  But it looks like we forget to catch the tableau.log statements and redirect them to console.out.

Thanks for the report @mradamlacey.  I would suggest just using console.log for now instead of tableau.log.  We output all of the console.log statements in the Tableau log files anyways, so tableau.log isn't necessary, you will see the same behavior with just console.log statements.

**Comment by jagreene** [comment]
I believe this is resolved with the new simulator as well

**Comment by lbrendanl** [comment]
Closing this, fixed in the v2 simulator.  We are no longer actively developing the v1 simulator (though it can still be used through our GH releases) so closing this as a won't fix.
