### ISSUE TITLE
Tableau Desktop 2019.4 Issue: Authorization error during the init phase, value of tableau.username disappears shortly

### ISSUE THREAD

**Issue by illonage** [tableau/webdataconnector#337]
We are encountering an issue with Tableau Desktop 2019.4 during the init phase: inside the init, the value of tableau.username is inconsistent. Half of the time, the value of tableau.username disappears shortly after it got set making the API call fails with an "Authorization Error".

**Comment by jozsi** [comment]
Hi,

Glad to see this on GitHub. I've reported the issue 2 months ago, can provide additional details via this channel as well.

But briefly: navigating or refreshing a WDC in Tableau 2019.4+ results in missing connection data.

I have not found a solid workaround. For example, doing a OAuth2'orization is almost impossible to do. Until recently we have told our users to stick to 2019.3, however, it's not a solution anymore, because Facebook recently dumped support for older browsers (like the one pre-2019.4 is based upon) and the OAuth2 flow breaks on their consent screen (that we can not control).

**Comment by illonage** [comment]
Hi all  - Great news! The fix should be the maintenance releases: 2019.4.5, 2020.1.1

**Comment by jozsi** [comment]
Dear @illonage - when are the aforementioned versions planned to be released to public?

**Comment by illonage** [comment]
Hi Jozsi, these maintenance releases should be released in the next weeks. I will update you in this thread when it is released. Thank you for your patience

**Comment by illonage** [comment]
Hello @jozsi - We just released the maintenance releases: https://www.tableau.com/support/releases/server

Can you try it and let me know if it is working :)
