### ISSUE TITLE
usg earthquake demo works in simulator but not in desktop

### ISSUE THREAD

**Issue by henryw374** [tableau/webdataconnector#410]
Hi, I have tableau 2019.3. I have successfully started the node server and simulated with the earthquake demo.

In the app, when I press to get the data, I first see a message saying 'Internal Error' and then on closing that another dialog which says  'The web data connector returned invalid data', and in the details of that says 'Error creating object for class TableInfo..' Error creating object for class ColumnInfo. Error: Unknown Data Type.

I have tried with a different version of the tableau js in that connector, but still no luck. 

Any ideas?

Thanks

**Comment by henryw374** [comment]
I have tried debugging with the built in debugger (as I am on 2019.3) https://tableau.github.io/webdataconnector/docs/wdc_debugging.html 

and I see the schemaCallback getting called, but that getData is never called - so it looks like that is consistent with the error message - ie somehow the earthquake example doesn't work in this version of tableau.

**Comment by theoutlander** [comment]
@henryw374 there have been some changes since 2019.4, but I'm not sure if the simulator has been changed to keep up with that. Can you try a couple of things:

1. Run this on the latest trial version of Tableau and see if you can repro the issue
2. If that works, try syncing to the simulator version that was released around your version of Tableau (2019.3 or 10.3.4?)

You can also inject logs by calling tableau.log('...') and those show up in the tableau log files.

**Comment by henryw374** [comment]
Ok thanks. It works on the latest trial version. Unfortunately, that version is not available to me.

I'm trying to find what version of the simulator was available when 2019.3 was released but unfortunately it looks like releases are not tracked in github https://github.com/tableau/webdataconnector/releases 

The question this comes down to though is what format does 2019.3 expect the data schema to be in?

According to the docs, it should be like this: https://github.com/tableau/webdataconnector/blob/master/Examples/js/earthquakeUSGS.js#L7-L28 

Log statements won't help unfortunately as it is in the callback call `schemaCallback([tableSchema]);` that it blows up.

**Comment by KeshiaRose** [comment]
Hi @henryw374, the Simulator hasn't changed for two years but even still it won't ever give an exact representation of how things will work in Desktop since we use a specific browser that is different than your personal browser. The main thing to keep in mind for WDCs in 2019.3 is that this version is before the latest in-product browser update and will not support modern JavaScript (ES6 etc.). However, the earthquake samples were written quite some time ago and work in 2019.3. You can test the earthquake sample hosted here and you should see that it works in 2019.3 (I just tested myself): https://tableau.github.io/webdataconnector/Examples/html/earthquakeUSGS.html Perhaps there is something else going on with your set up that is causing the issues. As for the structure, there are no differences between 2019.3 and now when it comes to the way the WDC expects the data.
-Keshia

**Comment by henryw374** [comment]
Thanks Keshia - I have tried with your link and on clicking 'get earthquake data' button I get the same error message as before about 'unknown data type'. 

So... any more ideas? It must be something about the specific version/build I am using I guess 

I think the company I'm doing this work for has some kind of support channel with Tableau so maybe going down that route could yield something.

I have been googling and found someone else had a problem with 2019.3 https://community.tableau.com/s/question/0D54T00000C5Ry7/wdc-data-not-added-to-sheet-in-20193 but it sounds like something different

**Comment by henryw374** [comment]
ok it's just been pointed out to me that we have tableau desktop 2020.1.2 available in the company now - and the earthquake demo https://tableau.github.io/webdataconnector/Examples/html/earthquakeUSGS.html does seem to work in that. Phew!

**Comment by theoutlander** [comment]
Glad you have a workaround!
