### ISSUE TITLE
Web Data Connector - Data refresh not working in tableau server 2020.3

### ISSUE THREAD

**Issue by javakishore** [tableau/webdataconnector#417]
I have created a WDC 2.0.1, it is working on tableau desktop 2020.3, I am able to create a data source based on this web data connector and I am able to extract data from the REST API.
Then I published my data source on Tableau Server 2020.3, I have created a workbook on top of it.
Everything works as expected.

The issue is that the Tableau Server never refreshes the Data Source neither by scheduled refresh nor by manual refresh.
Extract status showing in **progress** forever.

There is a submit page in the Web Data Connector, where the user key in the username and password of the REST API.
I have noticed that Tableau Server is not submitting the form upon the data extract.

1. WDC is working perfectly in Tableau Desktop
2. I have whitelisted the WDC URL in the server. 
3. Credentials are embedded into the Datasource.
4. Initial call is reaching to WDC server upon extract started.
5. Authentication form is not getting submitted and the call is not reaching the API server.

Below is my WDC code.

```
<html>
  <head>
    <title>Security Incidents</title>
    <meta http-equiv="Cache-Control" content="no-store" />

    <link
      href="/public/css/bootstrap.min.css"
      rel="stylesheet"
      type="text/css"
    />
    <script
      type="text/javascript"
      src="/public/javascript/jquery.min.js"
    ></script>
    <script
      type="text/javascript"
      src="/public/javascript/bootstrap.min.js"
    ></script>
    <script
      type="text/javascript"
      src="/public/javascript/tableauwdc-2.1.1.js"
    ></script>
    <script type="text/javascript">
      var myConnector = tableau.makeConnector();

      // Define the schema
      myConnector.getSchema = function (schemaCallback) {
        var cols = [
          {
            id: "csc_account",
            dataType: tableau.dataTypeEnum.string,
          },
          {
            id: "csc_number",
            dataType: tableau.dataTypeEnum.string,
          }         
        ];

        var tableSchema = {
          id: "Some_Data",
          columns: cols,
        };

        schemaCallback([tableSchema]);
      };

      // Download the data
      myConnector.getData = function (table, doneCallback) {
        const url = `${window.location.protocol}//${window.location.host}/get-details-api`;
        $.post(url, {
          username: tableau.username,
          password: tableau.password,
        }).done(function (data) {
          const tableData = [];
          data.forEach((item) => {
            tableData.push({
              csc_account: item.csc_account,
              csc_number: item.csc_number,              
            });
          });
          table.appendRows(tableData);
          doneCallback();
        });
      };

      tableau.registerConnector(myConnector);

      // Create event listeners for when the user submits the form
      $(document).ready(function () {
        $("#submitButton").click(function () {
          tableau.connectionName = "Security Incidents"; // This will be the data source name in Tableau
          tableau.username = $("#username").val();
          tableau.password = $("#password").val();
          tableau.submit(); // This sends the connector object to Tableau
        });
      });
    </script>
  </head>
 <body>
    <section class="jumbotron text-center">
      <div class="container col-lg-6 col-md-6 text-center">
        <h1 class="jumbotron-heading">Connect to Server</h1>
        <p>
          <input
            class="form-control"
            type="text"
            name="username"
            id="username"
            placeholder="Username"
          />
          <label class="sr-only" for="username">Username</label>
        </p>
        <p>
          <input
            class="form-control"
            type="password"
            name="password"
            id="password"
            placeholder="Password"
          />
          <label class="sr-only" for="password">Password or token</label>
        </p>
        <div>
          <input
            type="submit"
            value="Connect"
            id="submitButton"
            class="btn btn-lg btn-primary btn-success"
          />
        </div>
      </div>
    </section>
  </body>
</html>
```

**Comment by KeshiaRose** [comment]
Hi @javakishore, This is likely due to one or more URLs not being safe-listed on the server. Not only do you need to safe-list the WDC URL but also any other URLs your WDC connects to such as external JavaScript libraries, other local files (I see you have your libs locally), and the REST API you are pulling data from. Make sure to add all of these to your secondary safe list, for example:
`tsm data-access web-data-connectors add --name "My WDC" --url https://www.mysite.com:443/mywdc --secondary https://www.mysite.com/(.*),https://connectors.tableau.com/(.*),https://api.cooldatasource.com/(.*)`
You can confirm if this is the case by taking a look at the logs. Specifically, look in the backgrounder logs:  `C:\ProgramData\Tableau\Tableau Server\data\tabsvc\logs\backgrounder\tabprotosrv_backgrounder_#########.txt` or `/var/opt/tableau/tableau_server/data/tabsvc/logs/backgrounder/tabprotosrv_backgrounder_#########.txt` for something like 
> "Secondary whitelisting: does not find a corresponding entry for URL 'https://connectors.tableau.com/libs/tableauwdc-2.3.latest.js', hence it is not allowed"

Another thing to note is that the submission page that is shown when a user connects to the WDC for the first time is never accessed when refreshing the data source. Only the data gathering phase is run ([diagram](https://tableau.github.io/webdataconnector/docs/wdc_phases.html#diagram)), this means all information needed for the refresh needs to be in either tableau.connectionData or tableau.username/password. You already mentioned you were embedding the password when publishing so that part should be fine.
-Keshia

**Comment by javakishore** [comment]
Hi @KeshiaRose ,

Thank you so much for your help.
I managed to fix the issue. Initially I have whitelisted as below
`tsm data-access web-data-connectors add --name "WTA WDC" --url https://server:3000/wta-wdc/ --secondary https://server:3000/*`

but it is not sufficient, I need to whitelist all the static pages and other js reference also as below

`tsm data-access web-data-connectors add --name "WTA WDC" --url https://server:3000/wta-wdc/ --secondary "https://server:3000/public/css/bootstrap.min.css,https://server:3000/public/javascript/jquery.min.js,https://server:3000/public/javascript/bootstrap.min.js,https://server:3000/public/javascript/tableauwdc-2.1.1.js,https://server:3000/public/javascript/security-incidents.js,https://server:3000/*"`

**Comment by henryw374** [comment]
Would it be possible to use wildcards in the secondary list `*` for example so the wdc can load any resource?

Also can you have wildcards in the primary, so that many wdcs could be hosted on the same server without a need for a listing for each?

**Comment by KeshiaRose** [comment]
I don't think you can use wildcards on the primary URL but you can add (.*) to URLs in your secondary safelist.
