### ISSUE TITLE
Simulator "Fetch Data" State Misleading

### ISSUE THREAD

**Issue by jdomingu** [tableau/webdataconnector#85]
When I have multiple tables in the simulator and I click "Fetch Table Data" for one of them, I see that it does get the data for just that table. But all the Fetch buttons get a little spinner so it LOOKS like it is fetching all of them even though I selected just one.

**Comment by lbrendanl** [comment]
This issue is tricky, it would require a large refactor.  I purposely disabled all the fetch buttons because we don't have any sort of asynchronous functionality in the messaging layer.  We could definitely build it, but it would require a fairly large refactor.  We should definitely leave this open, but we likely won't get to it soon.

**Comment by lbrendanl** [comment]
We're just going to close this, realistically we won't ever do this.  Not worth the effort.
